/** @type {import('tailwindcss').Config} */
// Design tokens come from the "Warm Editorial" system in the original Stitch export.
module.exports = {
  content: ['./*.html', './assets/site.js'],
  theme: {
    extend: {
      colors: {
        "background": "#fcf9f8",
        "charcoal": "#262626",
        "cream": "#FFF5EC",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#ffb77d",
        "inverse-surface": "#303030",
        "ochre": "#b08b59",
        "ochre-dark": "#8d4f11",
        "ochre-light": "#f5ece2",
        "on-background": "#1b1c1c",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#6e3900",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6a635c",
        "on-secondary-fixed": "#1f1b16",
        "on-secondary-fixed-variant": "#4b4640",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#534439",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#504636",
        "on-tertiary-fixed": "#221a0d",
        "on-tertiary-fixed-variant": "#504536",
        "outline": "#857467",
        "outline-variant": "#d8c3b4",
        "primary": "#8d4f11",
        "primary-container": "#f4a460",
        "primary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#ffb77d",
        "sand": "#F4EFEB",
        "secondary": "#645d57",
        "secondary-container": "#eae1d8",
        "secondary-fixed": "#eae1d8",
        "secondary-fixed-dim": "#cec5bd",
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "surface-container-low": "#f6f3f2",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "surface-tint": "#8d4f11",
        "surface-variant": "#e4e2e1",
        "tertiary": "#685d4c",
        "tertiary-container": "#c3b4a0",
        "tertiary-fixed": "#f0e0cb",
        "tertiary-fixed-dim": "#d4c4b0"
},
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1120px',
        'margin-mobile': '20px',
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'section-gap': '96px',
        'stack-md': '32px',
      },
      fontFamily: {
        headline: ['"Libre Caslon Text"', 'Georgia', 'serif'],
        display: ['"Libre Caslon Text"', 'Georgia', 'serif'],
        body: ['"Source Serif 4"', 'Georgia', 'serif'],
        label: ['"Work Sans"', 'system-ui', 'sans-serif'],
        'headline-xl': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'headline-xl-mobile': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'headline-lg': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'headline-md': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'display-lg': ['"Libre Caslon Text"', 'Georgia', 'serif'],
        'body-lg': ['"Source Serif 4"', 'Georgia', 'serif'],
        'body-md': ['"Source Serif 4"', 'Georgia', 'serif'],
        'label-md': ['"Work Sans"', 'system-ui', 'sans-serif'],
        'label-sm': ['"Work Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
